export enum Services {
  DATABASE = "Database",
  RESEND = "Resend",
}

export enum ErrorCodes {
  INVALID_ROLE = "INVALID_ROLE",
  NOT_FOUND = "NOT_FOUND",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  CREATE_ENTITY_ERROR = "CREATE_ENTITY_ERROR",
  GET_ALL_ENTITIES_ERROR = "GET_ALL_ENTITIES_ERROR",
  GET_ENTITY_BY_ID_ERROR = "GET_ENTITY_BY_ID_ERROR",
  UPDATE_ENTITY_ERROR = "UPDATE_ENTITY_ERROR",
  DELETE_ENTITY_ERROR = "DELETE_ENTITY_ERROR",
  AUTH_ERROR = "AUTH_ERROR",
}
